# AI Bias Psychologist - Application Configuration
# This file contains general application settings and feature flags

app:
  name: "AI Bias Psychologist"
  version: "0.1.0"
  description: "A diagnostic tool for detecting cognitive biases in LLMs"
  debug: false
  log_level: "INFO"

# Database configuration
database:
  url: "sqlite:///./data/database/bias_psych.db"
  echo: false
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

# Data storage paths
storage:
  base_dir: "./data"
  responses_dir: "./data/responses"
  database_dir: "./data/database"
  exports_dir: "./data/exports"
  logs_dir: "./data/logs"
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation:
    enabled: true
    max_bytes: 10485760  # 10MB
    backup_count: 5
  console_output: true
  structured_logging: true

# Web dashboard configuration
dashboard:
  host: "0.0.0.0"
  port: 8000
  reload: false
  cors_origins: ["*"]
  static_files: "./src/ai_bias_psych/web/static"
  templates: "./src/ai_bias_psych/web/templates"
  
# Real-time updates
websocket:
  enabled: true
  ping_interval: 25
  ping_timeout: 10
  max_connections: 100

# Analytics and scoring
analytics:
  effect_size_threshold: 0.2
  significance_level: 0.05
  confidence_interval: 0.90
  min_sample_size: 10
  max_sample_size: 1000
  
# Sentiment analysis
sentiment:
  model: "vader"
  fallback_model: "textblob"
  confidence_threshold: 0.7
  
# Export settings
export:
  default_format: "json"
  available_formats: ["json", "csv", "html", "pdf"]
  include_metadata: true
  anonymize_responses: false
  
# Security settings
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
# Feature flags
features:
  real_time_dashboard: true
  batch_processing: true
  model_comparison: true
  trend_analysis: true
  export_functionality: true
  educational_content: true
  bias_mitigation_recommendations: false  # v0.1 scope
  
# Performance settings
performance:
  max_concurrent_requests: 10
  request_timeout: 30
  cache_responses: true
  cache_ttl: 3600  # 1 hour
  
# Monitoring and metrics
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  prometheus_enabled: false
  
# Development settings
development:
  hot_reload: false
  debug_toolbar: false
  mock_llm_responses: false
  test_mode: false
