# AI Bias Psychologist - Logging Configuration
# This file defines logging settings and structured logging configuration

# Logging levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level: "INFO"

# Log output configuration
output:
  console: true
  file: true
  structured: true

# File logging configuration
file_logging:
  enabled: true
  directory: "./data/logs"
  rotation:
    max_bytes: 10485760  # 10MB
    backup_count: 5
  files:
    main: "ai_bias_psych.log"
    probe_execution: "probe_execution.log"
    errors: "errors.log"
    llm_requests: "llm_requests.log"
    analytics: "analytics.log"

# Console logging configuration
console_logging:
  enabled: true
  format: "json"  # json or text
  colorize: true

# Structured logging configuration
structured_logging:
  enabled: true
  format: "json"
  processors:
    - "structlog.stdlib.filter_by_level"
    - "structlog.stdlib.add_logger_name"
    - "structlog.stdlib.add_log_level"
    - "structlog.stdlib.PositionalArgumentsFormatter"
    - "structlog.processors.TimeStamper"
    - "structlog.processors.StackInfoRenderer"
    - "structlog.processors.format_exc_info"
    - "structlog.processors.UnicodeDecoder"
    - "structlog.processors.JSONRenderer"

# Log context configuration
context:
  include_timestamp: true
  include_logger_name: true
  include_module_info: true
  include_process_info: false
  include_thread_info: false

# Probe execution logging
probe_logging:
  enabled: true
  log_level: "INFO"
  events:
    - "probe_start"
    - "probe_response"
    - "probe_error"
    - "bias_score"
    - "session_start"
    - "session_end"
  include_response_content: false  # Set to true for debugging
  include_prompt_content: false    # Set to true for debugging

# LLM request logging
llm_logging:
  enabled: true
  log_level: "INFO"
  events:
    - "request_start"
    - "request_complete"
    - "request_error"
    - "rate_limit_hit"
    - "retry_attempt"
  include_request_content: false   # Set to true for debugging
  include_response_content: false  # Set to true for debugging
  log_tokens: true
  log_costs: true

# Analytics logging
analytics_logging:
  enabled: true
  log_level: "INFO"
  events:
    - "score_calculation"
    - "statistical_analysis"
    - "trend_analysis"
    - "export_generation"
  include_raw_data: false  # Set to true for debugging

# Performance logging
performance_logging:
  enabled: true
  log_level: "INFO"
  events:
    - "slow_request"
    - "high_memory_usage"
    - "database_slow_query"
  thresholds:
    slow_request_ms: 5000
    high_memory_mb: 1000
    slow_query_ms: 1000

# Security logging
security_logging:
  enabled: true
  log_level: "WARNING"
  events:
    - "authentication_failure"
    - "authorization_failure"
    - "suspicious_activity"
    - "rate_limit_exceeded"

# Error handling
error_handling:
  log_exceptions: true
  log_stack_traces: true
  log_error_context: true
  max_error_message_length: 1000

# Log filtering
filtering:
  exclude_patterns:
    - "health_check"
    - "metrics"
  include_patterns: []
  sensitive_fields:
    - "api_key"
    - "password"
    - "token"
    - "secret"

# Log aggregation (for future use)
aggregation:
  enabled: false
  batch_size: 100
  flush_interval: 30
  endpoint: null
