name: Deploy DEV

on:
  push:
    branches: [ main ]  # must match the trust policy 'sub'

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::398128643426:role/gha-deploy-dev
          aws-region: us-east-2
          audience: sts.amazonaws.com
      - name: Terraform Init/Apply (DEV)
        working-directory: infra/envs/dev
        run: |
          terraform init
          terraform apply -auto-approve
